-- [IX] SEQUENCE : 순차번호 생성기, 대부분 인위적인 PK사용 용도
DROP SEQUENCE FRIEND_SEQ; -- 혹시 몰라 drop부터
CREATE SEQUENCE FRIEND_SEQ
        START WITH 1
        INCREMENT BY 1
        MAXVALUE 9999
        MINVALUE 1
        NOCYCLE
        NOCACHE;
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NUM NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(20) UNIQUE, -- UNIQUE : 유일, NULL허용
    TEL   VARCHAR2(20),
    LAST_MODIFYED DATE DEFAULT SYSDATE);

INSERT INTO FRIEND (NUM, NAME, PHONE) 
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동','010-9999-9999');
INSERT INTO FRIEND (NUM, NAME, PHONE, TEL) 
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동',NULL, '02-716-1006');
INSERT INTO FRIEND (NUM, NAME, PHONE, TEL) 
    VALUES (FRIEND_SEQ.NEXTVAL, '신길동','010-8888-8888',
            '02-716-1006');
INSERT INTO FRIEND 
    VALUES (FRIEND_SEQ.NEXTVAL, '김',NULL, NULL, SYSDATE);
SELECT * FROM FRIEND;
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 현재 시퀀스 값

-- 총 연습문제
-- 1~4
DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;
CREATE TABLE CUS_LEVEL(
    LEVELNO   NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL);
CREATE SEQUENCE CUS_SQ MAXVALUE 9999;
CREATE TABLE CUSTOMER(
    CNO      NUMBER(4)    PRIMARY KEY,
    CNAME    VARCHAR2(50) NOT NULL,
    JOINDATE DATE         DEFAULT SYSDATE,
    PHONE    VARCHAR2(50) UNIQUE,
    POINT    NUMBER,
    LEVELNO  NUMBER(1)    REFERENCES CUS_LEVEL(LEVELNO));
INSERT INTO CUS_LEVEL VALUES (1, 'VVIP');
INSERT INTO CUS_LEVEL VALUES (2, 'VIP');
INSERT INTO CUS_LEVEL VALUES (3, 'NORMAL');
INSERT INTO CUS_LEVEL VALUES (4, 'BLACK');
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL, '홍길동', 
        TO_DATE('20171017','YYYYMMDD'),'010-9999-9999',300,1);
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL, '이철수', 
        TO_DATE('20171112','YYYYMMDD'),'010-8888-8888',NULL,2);
SELECT * FROM CUSTOMER;
desc customer;

-- 5
SELECT CNO, CNAME, TO_CHAR(JOINDATE,'YYYY-MM-DD'), 
                    PHONE, POINT, LEVELNAME
    FROM CUS_LEVEL L, CUSTOMER C
    WHERE L.LEVELNO=C.LEVELNO;-- [IX] SEQUENCE : 순차번호 생성기, 대부분 인위적인 PK사용 용도
DROP SEQUENCE FRIEND_SEQ; -- 혹시 몰라 drop부터
CREATE SEQUENCE FRIEND_SEQ
        START WITH 1
        INCREMENT BY 1
        MAXVALUE 9999
        MINVALUE 1
        NOCYCLE
        NOCACHE;
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NUM NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(20) UNIQUE, -- UNIQUE : 유일, NULL허용
    TEL   VARCHAR2(20),
    LAST_MODIFYED DATE DEFAULT SYSDATE);

INSERT INTO FRIEND (NUM, NAME, PHONE) 
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동','010-9999-9999');
INSERT INTO FRIEND (NUM, NAME, PHONE, TEL) 
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동',NULL, '02-716-1006');
INSERT INTO FRIEND (NUM, NAME, PHONE, TEL) 
    VALUES (FRIEND_SEQ.NEXTVAL, '신길동','010-8888-8888',
            '02-716-1006');
INSERT INTO FRIEND 
    VALUES (FRIEND_SEQ.NEXTVAL, '김',NULL, NULL, SYSDATE);
SELECT * FROM FRIEND;
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 현재 시퀀스 값

-- 총 연습문제
-- 1~4
DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;
CREATE TABLE CUS_LEVEL(
    LEVELNO   NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL);
CREATE SEQUENCE CUS_SQ MAXVALUE 9999;
CREATE TABLE CUSTOMER(
    CNO      NUMBER(4)    PRIMARY KEY,
    CNAME    VARCHAR2(50) NOT NULL,
    JOINDATE DATE         DEFAULT SYSDATE,
    PHONE    VARCHAR2(50) UNIQUE,
    POINT    NUMBER,
    LEVELNO  NUMBER(1)    REFERENCES CUS_LEVEL(LEVELNO));
INSERT INTO CUS_LEVEL VALUES (1, 'VVIP');
INSERT INTO CUS_LEVEL VALUES (2, 'VIP');
INSERT INTO CUS_LEVEL VALUES (3, 'NORMAL');
INSERT INTO CUS_LEVEL VALUES (4, 'BLACK');
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL, '홍길동', 
        TO_DATE('20171017','YYYYMMDD'),'010-9999-9999',300,1);
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL, '이철수', 
        TO_DATE('20171112','YYYYMMDD'),'010-8888-8888',NULL,2);
SELECT * FROM CUSTOMER;
desc customer;

-- 5
SELECT CNO, CNAME, TO_CHAR(JOINDATE,'YYYY-MM-DD'), 
                    PHONE, POINT, LEVELNAME
    FROM CUS_LEVEL L, CUSTOMER C
    WHERE L.LEVELNO=C.LEVELNO;